# Chapter-23 - Numpy Practice Quesions Set-1

## Q1. Create an array of 7 zeros?

In [1]:
import numpy as np
# np.zeros(7)
# np.zeros(7,dtype=int)
# np.full(7,0)
print(f"Array of 7 zeros using np.zeros(7) : {np.zeros(7)}")
print(f"Array of 7 zeros using np.zeros(7,dtype=int) : {np.zeros(7,dtype=int)}")
print(f"Array of 7 zeros using np.full(7,0) : {np.full(7,0)}")

Array of 7 zeros using np.zeros(7) : [0. 0. 0. 0. 0. 0. 0.]
Array of 7 zeros using np.zeros(7,dtype=int) : [0 0 0 0 0 0 0]
Array of 7 zeros using np.full(7,0) : [0 0 0 0 0 0 0]


## Create an array of 9 ones?

In [2]:
# np.ones(9)
# np.ones(9,dtype=int)
# np.full(9,1)
print(f"Array of 9 ones using np.ones(9) : {np.ones(9)}")
print(f"Array of 9 ones using np.ones(9,dtype=int) : {np.ones(9,dtype=int)}")
print(f"Array of 9 ones using np.full(9,1) : {np.full(9,1)}")

Array of 9 ones using np.ones(9) : [1. 1. 1. 1. 1. 1. 1. 1. 1.]
Array of 9 ones using np.ones(9,dtype=int) : [1 1 1 1 1 1 1 1 1]
Array of 9 ones using np.full(9,1) : [1 1 1 1 1 1 1 1 1]


## Q3. Create an array of 10 fours?

In [3]:
# np.full(10,4)
# np.zeros(10,dtype=int)+4
# np.ones(10,dtype=int)+3
print(np.full(10,4))
print(np.zeros(10,dtype=int)+4)
print(np.ones(10,dtype=int)+3)

[4 4 4 4 4 4 4 4 4 4]
[4 4 4 4 4 4 4 4 4 4]
[4 4 4 4 4 4 4 4 4 4]


## Q4. Create an array of integers from 10 to 40?

In [4]:
print(np.arange(10,41))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]


## Q5. Create an array of integers from 10 to 40 which are even?

In [6]:
np.arange(10,41,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])

## Q6. Create an array of integers from 10 to 40 which are odd?

In [7]:
np.arange(11,41,2)

array([11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39])

## Q7. Create an array of integers from 10 to 40 which are divisible by 7?

In [12]:
# 1st way:
print(np.arange(14,41,7))

# 2nd way:
a = np.arange(10,41)
print(a)
print(a[a%7==0])

[14 21 28 35]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40]
[14 21 28 35]


## Q8. Create a numpy array having 10 numbers starts from 24 but only even numbers?

In [11]:
# 1st way:
print(f"using np.arange(24,43,2): {np.arange(24,43,2)}")

# 2nd way:
a = np.arange(24,50)
a = a[a%2==0]
print(f"using np.resize(a,10) : {np.resize(a,10)}")

using np.arange(24,43,2): [24 26 28 30 32 34 36 38 40 42]
using np.resize(a,10) : [24 26 28 30 32 34 36 38 40 42]


## Q9. Create a 4X4 matrix with elements from 1 to 16?

In [15]:
np.arange(1,17).reshape(4,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## Q10. Create a 4X4 identity matrix?

In [16]:
print(f"using np.eye(4) : \n {np.eye(4)}")
print(f"using np.identity(4) :\n {np.identity(4)}")

using np.eye(4) : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
using np.identity(4) :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## Q11. By using numpy module, generate ndarray with random numbers from 1 to 100 with the shape:(2,3,4)?

In [17]:
np.random.randint(1,101,size=(2,3,4))

array([[[50, 54, 80, 25],
        [76, 76, 10, 23],
        [97, 28,  1, 33]],

       [[43, 78, 44, 46],
        [69, 12, 38, 70],
        [25,  1, 82, 31]]])

## Q12. By using numpy module, generate a random number between 0 and 1?

In [18]:
np.random.rand()

0.14872545200345866

## Q13. By using numpy module, generate an array of 10 random samples from a uniform distribution over [0,1)?

In [19]:
np.random.rand(10)

array([0.04410494, 0.99281805, 0.86596311, 0.63254419, 0.53836484,
       0.62971424, 0.15492951, 0.80546328, 0.07944047, 0.67682372])

## Q14. By using numpy module, generate an array of 10 random samples from a uniform distribution over [10,20)?

In [20]:
# np.random.uniform(low=0.0,high=1.0,size=None)
np.random.uniform(10,20,10)

array([10.13827107, 13.62529954, 10.93040852, 16.64554335, 19.40447865,
       13.83889201, 11.6213692 , 10.85964281, 11.84565738, 11.06253163])

## Q15. By using numpy module, generate an array of 10 random samples from a standard normal distribution of mean 0 and standard deviation 1?

In [21]:
np.random.randn(10)

array([-0.18138902,  0.4065823 , -1.58697766,  0.58668406, -1.65045796,
       -1.03464804, -0.81783782, -1.99665034,  0.27058323,  0.30286414])

## Q16. By using numpy module, generate an array of 10 random samples from a standard normal distribution of mean 15 and and stadard deviation 4?

In [22]:
# normal(loc=0.0, scale=1.0, size=None)
# loc--->mean
# scale--->standard deviation
a = np.random.normal(15,4,10)
a

array([20.36439847, 22.02578084, 17.95415554, 12.19892251, 14.30547671,
       16.85168322, 13.92844455, 12.10299385, 12.35731225, 11.66229273])

## Q17. Create an array of 10 linearly spaced points between 1 and 100?

In [23]:
np.linspace(1,100,10,retstep=True)

(array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.]), 11.0)

## Q18. Create an array of 15 linearly spaced points between 0 and 1?

In [24]:
np.linspace(0,1,15,retstep=True)

(array([0.        , 0.07142857, 0.14285714, 0.21428571, 0.28571429,
        0.35714286, 0.42857143, 0.5       , 0.57142857, 0.64285714,
        0.71428571, 0.78571429, 0.85714286, 0.92857143, 1.        ]),
 0.07142857142857142)

# Chapter-24 - Numpy Practice Quesions Set-2

In [25]:
import numpy as np
a = np.arange(1,37).reshape(6,6)
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

## Q1. How to access element 16?

In [26]:
print(f"a[2][3] ==> {a[2][3]}")
print(f"a[2,3] ==> {a[2,3]}")

a[2][3] ==> 16
a[2,3] ==> 16


## Q2. To get the following array: array([[2, 3, 4, 5]])

In [27]:
oned_array = a[0,1:5]
twod_array = a[0:1,1:5]
print(f"using with indexing : {oned_array}")
print(f"using with slicing : {twod_array}")

using with indexing : [2 3 4 5]
using with slicing : [[2 3 4 5]]


## Q3. To get the following array: array([[2, 3, 4, 5]])

In [28]:
oned_array = a[0,1:5]
twod_array = a[0:1,1:5]
print(f"using with indexing : {oned_array}")
print(f"using with slicing : {twod_array}")

using with indexing : [2 3 4 5]
using with slicing : [[2 3 4 5]]


## Q4. To get the following array

array([[ 1, 2, 3, 4, 5, 6],<br>
[31, 32, 33, 34, 35, 36]])

In [29]:
a[::5,:]

array([[ 1,  2,  3,  4,  5,  6],
       [31, 32, 33, 34, 35, 36]])

## Q5. To get the following array
array([[ 9, 10],<br>
[15, 16],<br>
[21, 22]])

In [30]:
a[1:4,2:4]

array([[ 9, 10],
       [15, 16],
       [21, 22]])

## Q6. Create 1-D array with all even numbers of a?

In [31]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36])

## Q7. Create a 1-D array with elements of a which are divisible by 5?

In [32]:
a[a%5==0]

array([ 5, 10, 15, 20, 25, 30, 35])

## Q8. Create 1-D array with elements 8,17,26 and 35. We have to use elements of a?

In [33]:
# a[[row_indices],[column_indices]]
a[[1,2,4,5],[1,4,1,4]]

array([ 8, 17, 26, 35])

## Q9. Select minimum element of this ndarray?

In [35]:
# np.amin(a)
# np.min(a)
# a.min()
print(f"np.amin(a) ==> {np.amin(a)}")
print(f"np.min(a) ==> {np.min(a)}")
print(f"a.min() ==> {a.min()}")

np.amin(a) ==> 1
np.min(a) ==> 1
a.min() ==> 1


## Q10. Select maximum element of this ndarray?

In [34]:
# np.amax(a)
# np.max(a)
# a.max()
print(f"np.amax(a) ==> {np.amax(a)}")
print(f"np.max(a) ==> {np.max(a)}")
print(f"a.max() ==> {a.max()}")

np.amax(a) ==> 36
np.max(a) ==> 36
a.max() ==> 36


## Q11. Find sum of elements present inside this array?

In [36]:
print(f"np.sum(a) ==> {np.sum(a)}")
print(f"a.sum() ==> {a.sum()}")

np.sum(a) ==> 666
a.sum() ==> 666


## Q12. Find sum of elements along axis-0?

In [37]:
print(f"np.sum(a,axis=0) ==> {np.sum(a,axis=0)}")
print(f"a.sum(axis=0) ==> {a.sum(axis=0)}")

np.sum(a,axis=0) ==> [ 96 102 108 114 120 126]
a.sum(axis=0) ==> [ 96 102 108 114 120 126]


## Q13. Find mean of this array?

In [38]:
print(f"np.mean(a) ==> {np.mean(a)}")
print(f"a.mean() ==> {a.mean()}")

np.mean(a) ==> 18.5
a.mean() ==> 18.5


## Q14. Find median of this array?

In [39]:
print(f"np.median(a) ==> {np.median(a)}")

np.median(a) ==> 18.5


## Q15. Find variance of this array?

In [40]:
print(f"np.var(a) ==> {np.var(a)}")
print(f"a.var() ==> {a.var()}")

np.var(a) ==> 107.91666666666667
a.var() ==> 107.91666666666667


## Q16. Find standard deviation of this array?

In [41]:
print(f"np.std(a) ==> {np.std(a)}")
print(f"a.std() ==> {a.std()}")

np.std(a) ==> 10.388294694831615
a.std() ==> 10.388294694831615


# Chapter-25 - Numpy Quiz Questions

## Q1. Consider the following code: 

import numpy as np <br>
a = np.array([])<br>
print(a.shape)<br>

What is the output ? </code><br>
• A. (0,)<br>
• B. (1,)<br>
• C. (1,1)<br>
• D. 0 <br>

Ans - A

In [42]:
import numpy as np
a = np.array([])
print(a.shape)

(0,)


## Q2. Consider the following code: 

import numpy as np <br>
a = np.arange(10,20,-1) <br>
b =a.reshape(5,2) <br>

print(b.flatten())<br>
• A. [10 11 12 13 14 15 16 17 18 19]<br>
• B. [20 19 18 17 16 15 14 13 12 11]<br>
• C. array([])<br>
• D. ValueError<br><br>
Ans: D

In [43]:
import numpy as np
a = np.arange(10,20,-1)
b = a.reshape(5,2)
print(b.flatten())

ValueError: cannot reshape array of size 0 into shape (5,2)

##  Refer to the  pdf