# Chapter-14 - How to insert elements into ndarray

## How to insert elements into ndarray
• **insert()** ==> inserting the element at the required position<br>
• **append()** ==> inserting the element at the end

### insert()

In [3]:
import numpy as np
help(np.insert)

Help on function insert in module numpy:

insert(arr, obj, values, axis=None)
    Insert values along the given axis before the given indices.
    
    Parameters
    ----------
    arr : array_like
        Input array.
    obj : int, slice or sequence of ints
        Object that defines the index or indices before which `values` is
        inserted.
    
        .. versionadded:: 1.8.0
    
        Support for multiple insertions when `obj` is a single scalar or a
        sequence with one element (similar to calling insert multiple
        times).
    values : array_like
        Values to insert into `arr`. If the type of `values` is different
        from that of `arr`, `values` is converted to the type of `arr`.
        `values` should be shaped so that ``arr[...,obj,...] = values``
        is legal.
    axis : int, optional
        Axis along which to insert `values`.  If `axis` is None then `arr`
        is flattened first.
    
    Returns
    -------
    out : ndarray
        A

In [1]:
# insert(array, obj, values, axis=None)
# Insert values along the given axis before the given indices.

# obj-->Object that defines the index or indices before which 'values' are inserted.
# values--->Values to insert into array.
# axis ---->Axis along which to insert 'values'.

#### 1-D arrays

In [4]:
# To insert 7777 before index 2
a = np.arange(10)
b = np.insert(a,2,7777)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [   0    1 7777    2    3    4    5    6    7    8    9]


In [5]:
# To insert 7777 before indexes 2 and 5.
a = np.arange(10)
b = np.insert(a,[2,5],7777)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [   0    1 7777    2    3    4 7777    5    6    7    8    9]


In [6]:
# To insert 7777 before index 2 and 8888 before index 5?
a = np.arange(10)
b = np.insert(a,[2,5],[7777,8888])
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [   0    1 7777    2    3    4 8888    5    6    7    8    9]


In [7]:
# shape mismatch
a = np.arange(10)
b = np.insert(a,[2,5],[7777,8888,9999])
print(f"array a : {a}")
print(f"array b : {b}")

ValueError: shape mismatch: value array of shape (3,) could not be broadcast to indexing result of shape (2,)

In [8]:
# shape mismatch
a = np.arange(10)
b = np.insert(a,[2,5,7],[7777,8888])
print(f"array a : {a}")
print(f"array b : {b}")

ValueError: shape mismatch: value array of shape (2,) could not be broadcast to indexing result of shape (3,)

In [9]:
a = np.arange(10)
b = np.insert(a,[2,5,5],[777,888,999])
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [  0   1 777   2   3   4 888 999   5   6   7   8   9]


In [10]:
# IndexError
a = np.arange(10)
b = np.insert(a,25,7777)
print(f"array a : {a}")
print(f"array b : {b}")

IndexError: index 25 is out of bounds for axis 0 with size 10

**Note**<br>
• All the insertion points(indices) are identified at the beginning of the insert operation<br>
• Array should contain only homogeneous elements<br>
• By using insert() function, if we are trying to insert any other type element, then that element will be converted to array type automatically before insertion.<br>
• If the conversion is not possible then we will get error.

In [11]:
# the original array contains int values. If inserted value is float then the float value
# is converted to the array type i.e., int. There may be data loss in this scenario
a = np.arange(10)
b = np.insert(a,2,123.456)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [  0   1 123   2   3   4   5   6   7   8   9]


In [12]:
a = np.arange(10)
b = np.insert(a,2,True)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [0 1 1 2 3 4 5 6 7 8 9]


In [13]:
a = np.arange(10)
b = np.insert(a,2,'GK')
print(f"array a : {a}")
print(f"array b : {b}")

ValueError: invalid literal for int() with base 10: 'GK'

In [14]:
a = np.arange(10)
b = np.insert(a,2,10+20j)
print(f"array a : {a}")
print(f"array b : {b}")

TypeError: can't convert complex to int

#### Summary for 1-D arrays while insertion
• The number of indices and the number of elements should be matched.<br>
• Out of range index is not allowed.<br>
• Elements will be converted automatically to the array type

#### 2-D arrays
• If we are trying to insert elements into multi dimensional arrays, compulsory we have to provide axis<br>
• If we are not providing axis value, then default value None will be considered<br>
• In this case, array will be flatten to 1-D array and then insertion will be happend.<br>
• axis=0 means rows (axis=-2)<br>
• axis=1 means columns (axis=-1)

In [15]:
# if the axis is not defined for 2-D arrays, None is selected by default
# here the 2-D array flatten to 1-D array and insertion will be happened
a = np.array([[10,20],[30,40]])
b = np.insert(a,1,100)
print(f"array a :\n {a}")
print(f"array b : {b}")

array a :
 [[10 20]
 [30 40]]
array b : [ 10 100  20  30  40]


<img src="images\insert2d.JPG" alt="insert2d" width="600" height="600">

In [16]:
# insert the elements along the axis=1 or axis=-1 ==> rows are inserted
a = np.array([[10,20],[30,40]])
b = np.insert(a,1,100,axis=1)
c = np.insert(a,1,100,axis=-1)
print(f"array a :\n {a}")
print(f"array b :\n {b}")
print(f"array c :\n {c}")

array a :
 [[10 20]
 [30 40]]
array b :
 [[ 10 100  20]
 [ 30 100  40]]
array c :
 [[ 10 100  20]
 [ 30 100  40]]


In [17]:
# to insert multiple rows
a = np.array([[10,20],[30,40]])
b = np.insert(a,1,[[100,200],[300,400]],axis=0)
print(f"array a :\n {a}")
print(f"array b :\n {b}")

array a :
 [[10 20]
 [30 40]]
array b :
 [[ 10  20]
 [100 200]
 [300 400]
 [ 30  40]]


In [18]:
# to insert multiple columns
a = np.array([[10,20],[30,40]])
b = np.insert(a,1,[[100,200],[300,400]],axis=1)
print(f"array a :\n {a}")
print(f"array b :\n {b}")

array a :
 [[10 20]
 [30 40]]
array b :
 [[ 10 100 300  20]
 [ 30 200 400  40]]


In [19]:
# ValueError
a = np.array([[10,20],[30,40]])
b = np.insert(a,1,[100,200,300],axis=0)
print(f"array a :\n {a}")
print(f"array b :\n {b}")

ValueError: could not broadcast input array from shape (1,3) into shape (1,2)

### append()
• By using insert() function, we can insert elements at our required index position.<br>
• If we want to add elements always at end of the ndarray, then we have to go for
append() function.

In [ ]:
import numpy as np
help(np.append)

#### 1-D arrays
• If appended element type is not same type of array, then elements conversion will be happend such that all elements of same common type.

In [20]:
# append 100 element to the existing array of int
a = np.arange(10)
b = np.append(a,100)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [  0   1   2   3   4   5   6   7   8   9 100]


In [21]:
# if the inserted element is not the type of the array then common type conversion happened
a = np.arange(10)
b = np.append(a,20.5)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [ 0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  20.5]


In [22]:
a = np.arange(10)
b = np.append(a,"GK")
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : ['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' 'GK']


In [23]:
a = np.arange(10)
b = np.append(a,True)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [0 1 2 3 4 5 6 7 8 9 1]


In [24]:
a = np.arange(10)
b = np.append(a,20+15j)
print(f"array a : {a}")
print(f"array b : {b}")

array a : [0 1 2 3 4 5 6 7 8 9]
array b : [ 0. +0.j  1. +0.j  2. +0.j  3. +0.j  4. +0.j  5. +0.j  6. +0.j  7. +0.j
  8. +0.j  9. +0.j 20.+15.j]


#### 2-D arrays
• If we are not specifying axis, then input array will be flatten to 1-D array and then append will be performed.<br>
• If we are providing axis, then all the input arrays must have same number of dimensions, and same shape of provided axis.<br>
• if axis-0 is taken then the obj should match with the number of columns of the input array<br>
• if axis-1 is taken then the obj should match with the number of rows of the input array


In [25]:
# here axis is not specified so the default "None" will be taken and flatten to 1-D array & insertion
a = np.array([[10,20],[30,40]])
b = np.append(a,70)
print(f"array a :\n {a}")
print(f"array b : {b}")

array a :
 [[10 20]
 [30 40]]
array b : [10 20 30 40 70]


In [26]:
# axis=0 ==> along rows
# Value Error : i/p array is 2-D and appended array is 0-D
a = np.array([[10,20],[30,40]])
b = np.append(a,70,axis=0) # appended is 0-D => 70
print(f"array a :\n {a}")
print(f"array b : {b}")

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 0 dimension(s)

In [27]:
# Value Error : i/p array is 2-D and appended array is 1-D
a = np.array([[10,20],[30,40]])
b = np.append(a,[70,80],axis=0) # appended is 1-D => [70,80]
print(f"array a :\n {a}")
print(f"array b : {b}")

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [29]:
# i/p array is 2-D and appended array is 2-D
a = np.array([[10,20],[30,40]])
b = np.append(a,[[70,80]],axis=0) # appended is 2-D => [[70,80]]
print(f"array a :\n {a}")
print(f"array b : {b}")

array a :
 [[10 20]
 [30 40]]
array b : [[10 20]
 [30 40]
 [70 80]]


In [30]:
# axis=1 along colums
# Value Error : i/p array is Size 2 and appended element is size 1
a = np.array([[10,20],[30,40]])
b = np.append(a,[[70,80]],axis=1) # appended is size 1 => [[70,80]]
print(f"array a :\n {a}")
print(f"array b : {b}")

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

In [31]:
a = np.array([[10,20],[30,40]])
b = np.append(a,[[70],[80]],axis=1)
print(f"array a :\n {a}")
print(f"array b :\n {b}")

array a :
 [[10 20]
 [30 40]]
array b :
 [[10 20 70]
 [30 40 80]]


In [32]:
# multiple columns
a = np.array([[10,20],[30,40]])
b = np.append(a,[[70,80],[90,100]],axis=1)
print(f"array a :\n {a}")
print(f"array b :\n {b}")

array a :
 [[10 20]
 [30 40]]
array b :
 [[ 10  20  70  80]
 [ 30  40  90 100]]


In [33]:
# Consider the array?
a = np.arange(12).reshape(4,3)
# Which of the following operations will be performed successfully?
# A. np.append(a,[[10,20,30]],axis=0) #valid
# B. np.append(a,[[10,20,30]],axis=1) #invalid
# C. np.append(a,[[10],[20],[30]],axis=0) #invalid
# D. np.append(a,[[10],[20],[30],[40]],axis=1) #valid
# E. np.append(a,[[10,20,30],[40,50,60]],axis=0) #valid
# F. np.append(a,[[10,20],[30,40],[50,60],[70,80]],axis=1) #valid

In [34]:
np.append(a,[[10,20,30]],axis=0) #valid

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [10, 20, 30]])

In [35]:
np.append(a,[[10,20,30]],axis=1) #invalid

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 4 and the array at index 1 has size 1

In [36]:
np.append(a,[[10],[20],[30]],axis=0) #invalid

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 1

In [37]:
np.append(a,[[10],[20],[30],[40]],axis=1) #valid

array([[ 0,  1,  2, 10],
       [ 3,  4,  5, 20],
       [ 6,  7,  8, 30],
       [ 9, 10, 11, 40]])

In [38]:
np.append(a,[[10,20,30],[40,50,60]],axis=0) #valid

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [10, 20, 30],
       [40, 50, 60]])

In [39]:
np.append(a,[[10,20],[30,40],[50,60],[70,80]],axis=1) #valid

array([[ 0,  1,  2, 10, 20],
       [ 3,  4,  5, 30, 40],
       [ 6,  7,  8, 50, 60],
       [ 9, 10, 11, 70, 80]])

In [40]:
a = np.arange(12).reshape(4,3)
print(a)
b = np.append(a,[[10],[20],[30],[40]],axis=1)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2 10]
 [ 3  4  5 20]
 [ 6  7  8 30]
 [ 9 10 11 40]]


In [41]:
a = np.arange(12).reshape(4,3)
print(a)
b = np.append(a,[[10,50],[20,60],[30,70],[40,80]],axis=1)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2 10 50]
 [ 3  4  5 20 60]
 [ 6  7  8 30 70]
 [ 9 10 11 40 80]]


## insert() vs append()

| Function  | Description                                                          |
|-----------|----------------------------------------------------------------------|
| `insert()`| By using the insert() function, we can insert elements at our required index position. |
| `append()`| By using the append() function, we can add elements always at the end of ndarray.   |

# Chapter-15 - How to delete elements from ndarray

## How to delete elements from ndarray

We can delete elements of ndarray by using delete() function.
<br>
**delete(arr, obj, axis=None)**<br>

• obj can be int, array of ints or slice<br>
• for multi-dimensional arrays we must have to specify the axis, other-wise the default axis=None will be considered. In this case first the array is flatten to the 1-D array and deletion will be performed

In [ ]:
import numpy as np
help(np.delete)

## 1-D arrays

In [42]:
# To delete a single element of 1-D array at a specified index
a = np.arange(10,101,10)
b = np.delete(a,3) # to delete the element present at 3rd index
print(f"array a : {a}")
print(f"array b : {b}")

array a : [ 10  20  30  40  50  60  70  80  90 100]
array b : [ 10  20  30  50  60  70  80  90 100]


In [43]:
# To delete elements of 1-D array at a specified indices
a = np.arange(10,101,10)
b = np.delete(a,[0,4,6]) # to delete elements present at indices:0,4,6
print(f"array a : {a}")
print(f"array b : {b}")

array a : [ 10  20  30  40  50  60  70  80  90 100]
array b : [ 20  30  40  60  80  90 100]


In [44]:
# To delete elements of 1-D array from a specified range using numpy np.s_[]
a = np.arange(10,101,10)
b = np.delete(a,np.s_[2:6]) # to delete elements from 2nd index to 5th index
print(f"array a : {a}")
print(f"array b : {b}")

array a : [ 10  20  30  40  50  60  70  80  90 100]
array b : [ 10  20  70  80  90 100]


In [45]:
# To delete elements of 1-D array from a specified range using python range
# this is applicable only for 1-D arrays.
a = np.arange(10,101,10)
b = np.delete(a,range(2,6)) # to delete elements from 2nd index to 5th index
print(f"array a : {a}")
print(f"array b : {b}")

array a : [ 10  20  30  40  50  60  70  80  90 100]
array b : [ 10  20  70  80  90 100]


## 2-D arrays

• Here we have to provide axis.<br>
• If we are not specifying access then array will be flatten(1-D) and then deletion will
be happend.

In [46]:
# without providing the axis. defautl axis=None will be taken
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,1)
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [ 1  3  4  5  6  7  8  9 10 11 12]


In [47]:
# axis=0. deleting the specifie row
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,1,axis=0) # row at index 1 will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[ 1  2  3]
 [ 7  8  9]
 [10 11 12]]


In [48]:
# axis=0. deleting the specified rows
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,[1,3],axis=0) # row at index 1 and index 3 will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[1 2 3]
 [7 8 9]]


In [49]:
# axis=0. deleting the specified range of rows
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,np.s_[0:3],axis=0) # rows from index-0 to index-(3-1) will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[10 11 12]]


In [50]:
# axis=0. deleting the specified range of rows with step value
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,np.s_[::2],axis=0) # to delete every 2nd row (alternative row) from
index-0
print(f"array a : \n {a}")
print(f"array b : \n {b}")

NameError: name 'index' is not defined

In [51]:
# axis=1. deleting the specifie column
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,1,axis=1) # column at index 1 will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[ 1  3]
 [ 4  6]
 [ 7  9]
 [10 12]]


In [52]:
# axis=1. deleting the specified colunns
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,[1,2],axis=1) # columns at index 1 and index 2 will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[ 1]
 [ 4]
 [ 7]
 [10]]


In [53]:
# axis=1. deleting the specified range of columns
a = np.arange(1,13).reshape(4,3)
b = np.delete(a,np.s_[0:2],axis=1) # rows from index-0 to index-(2-1) will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
array b : 
 [[ 3]
 [ 6]
 [ 9]
 [12]]


## 3-D arrays

In [54]:
# axis= None
a = np.arange(24).reshape(2,3,4)
b = np.delete(a,3) # flatten to 1-D array and element at 3rd index will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b : 
 [ 0  1  2  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [55]:
# axis=0. Delete a 2-D array at the specified index
a = np.arange(24).reshape(2,3,4)
b = np.delete(a,0,axis=0) # 2-D array at index 0 will be deleted
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b : 
 [[[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [56]:
# axis=1. Delete a row at the specified index from every 2-D array.
a = np.arange(24).reshape(2,3,4)
b = np.delete(a,0,axis=1) # Row at index 0 will be deleted from every 2-D array
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b : 
 [[[ 4  5  6  7]
  [ 8  9 10 11]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [57]:
# axis=1. Delete a column at the specified index from every 2-D array.
a = np.arange(24).reshape(2,3,4)
b = np.delete(a,1,axis=2) # column at index 1 will be deleted from every 2-D array
print(f"array a : \n {a}")
print(f"array b : \n {b}")

array a : 
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
array b : 
 [[[ 0  2  3]
  [ 4  6  7]
  [ 8 10 11]]

 [[12 14 15]
  [16 18 19]
  [20 22 23]]]


## case study

Consider the following array<br>

array([[ 0, 1, 2], [ 3, 4, 5], [ 6, 7, 8], [ 9, 10, 11]])<br>

Delete last row and insert following row in that place:==> [70,80,90]

In [58]:
# Solution for the case study
# Step:1 ==> create the required ndarray
a = np.arange(12).reshape(4,3)

# Step:2 ==> Delete the last row.
# We have to mention the axis as axis=0 for rows.
# obj value we can take as -1 , which represents the last row
b = np.delete(a,-1,axis=0)
print("Original Array")
print(f"array a : \n {a}")
print("After deletion the array ")
print(f"array b : \n {b}")

# Step:3 ==> we have to insert the row [70.80.90] at the end
# for this we can use append() function with axis=0
c = np.append(b,[[70,80,90]],axis=0)
print("After insertion the array ")
print(f"array c : \n {c}")

Original Array
array a : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After deletion the array 
array b : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
After insertion the array 
array c : 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [70 80 90]]


## Summary

• **insert()** ==> Insert elements into an array at specified index.<br>
• **append()** ==> Append elements at the end of an array.<br>
• **delete()** ==> Delete elements from an array.

# Chapter-16 - Matrix multiplication by using dot() function

## Matrix multiplication by using dot() function

• For a given two ndarrays a,b, if we perform a*b ==> element level multiplication will be happened<br>
• To perform matrix level multiplication we have to use dot() function<br>
• dot() function in available in numpy module<br>
• dot() method is present in ndarray class also

In [ ]:
# dot() function in numpy module
import numpy as np
help(np.dot)

In [ ]:
# dot() method in ndarray class
help(np.ndarray.dot)

In [59]:
# Element level multiplication
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
print(f"array a : \n {a}")
print(f"array b : \n {b}")
print("Element level multiplication ")
ele_multiplication = a* b
print(f"array b : \n {ele_multiplication}")

array a : 
 [[10 20]
 [30 40]]
array b : 
 [[1 2]
 [3 4]]
Element level multiplication 
array b : 
 [[ 10  40]
 [ 90 160]]


<img src="images\dot_product.JPG" alt="dot_product" width="600" height="600">

In [60]:
# matrix multiplication using dot() function in numpy module
a = np.array([[10,20],[30,40]])
b = np.array([[1,2],[3,4]])
dot_product = np.dot(a,b)
print(f"array a : \n {a}")
print(f"array b : \n {b}")
print(f"Matrix multiplication:\n {dot_product} ")

array a : 
 [[10 20]
 [30 40]]
array b : 
 [[1 2]
 [3 4]]
Matrix multiplication:
 [[ 70 100]
 [150 220]] 


<img src="images\matrix_multiplication.JPG" alt="dot_product" width="700" height="600">

# Chapter-17 - Importance of matrix class in numpy library

## Importance of matrix class in numpy library

1-D array is called => Vector<br>
2-D array is called => Matrix<br>

• matrix class is specially designed class to create 2-D arrays.

In [ ]:
import numpy as np
help(np.matrix)

## creating 2-D arrays

• By using matrix class<br>
• By using ndarray class<br>

**class matrix(ndarray)<br>
matrix(data, dtype=None, copy=True)**

• data : array_like or string<br>
• If data is a string, it is interpreted as a matrix with commas or spaces separating columns, and semicolons separating rows.<br>

**Parameters**

**1. data : array_like or string**
• If data is a string, it is interpreted as a matrix with commas
• or spaces separating columns, and semicolons separating rows.

**2. dtype : data-type**
• Data-type of the output matrix.

**3. copy : bool**
• If data is already an ndarray, then this flag determines
• whether the data is copied (the default), or whether a view is constructed.

In [62]:
# Creating matrix object from string
# a = np.matrix('col1 col2 col3;col1 col2 col3')
# a = np.matrix('col1,col2,col3;col1,col2,col3')
a = np.matrix('10,20;30,40')
b = np.matrix('10 20;30 40')
print(f"type of a : type(a)")
print(f"type of b : type(b)")
print(f"Matrix object creation from string with comma : \n{a}")
print(f"Matrix object creation from string with space : \n{b}")

type of a : type(a)
type of b : type(b)
Matrix object creation from string with comma : 
[[10 20]
 [30 40]]
Matrix object creation from string with space : 
[[10 20]
 [30 40]]


In [63]:
# Creating matrix object from nested list
a = np.matrix([[10,20],[30,40]])
a

matrix([[10, 20],
        [30, 40]])

In [64]:
# create a matrix from ndarray
a = np.arange(6).reshape(3,2)
b = np.matrix(a)
print(f"type of a : type(a)")
print(f"type of b : type(b)")
print(f'ndarray :\n {a}')
print(f'matrix :\n {b}')

type of a : type(a)
type of b : type(b)
ndarray :
 [[0 1]
 [2 3]
 [4 5]]
matrix :
 [[0 1]
 [2 3]
 [4 5]]


## + operator in ndarray and matrix

• In case of both ndarray and matrix + operator behaves in the same way

<img src="images\plus_operator.JPG" alt="plus_operator" width="700" height="600">

In [65]:
# + operator in ndarray and matrix
a = np.array([[1,2],[3,4]])
m = np.matrix([[1,2],[3,4]])
addition_a = a+a
addition_m = m+m
print(f'ndarray addition :\n {addition_a}')
print(f'matrix addition :\n {addition_m}')

ndarray addition :
 [[2 4]
 [6 8]]
matrix addition :
 [[2 4]
 [6 8]]


## * operator in ndarray and matrix

• In case of ndarray * operator performs element level multiplication<br>
• In case of matrix * operator performs matrix multiplication<br>

<img src="images\mul_operator.JPG" alt="plus_operator" width="700" height="600">

In [66]:
# * operator in ndarray and matrix
a = np.array([[1,2],[3,4]])
m = np.matrix([[1,2],[3,4]])
element_mul = a*a
matrix_mul = m*m
print(f'ndarray multiplication :\n {element_mul}')
print(f'matrix multiplication :\n {matrix_mul}')

ndarray multiplication :
 [[ 1  4]
 [ 9 16]]
matrix multiplication :
 [[ 7 10]
 [15 22]]


## ** operator in ndarray and
• In case of ndarray ** operator performs power operation at element level<br>
• In case of matrix ** operator performs power operation at matrix level<br>
m ** 2 ==> m *m<br>

<img src="images\power_operator.JPG" alt="plus_operator" width="700" height="600">

In [67]:
# ** operator in ndarray and matrix
a = np.array([[1,2],[3,4]])
m = np.matrix([[1,2],[3,4]])
element_power = a**2
matrix_power = m**2
print(f'ndarray power :\n {element_power}')
print(f'matrix power :\n {matrix_power}')

ndarray power :
 [[ 1  4]
 [ 9 16]]
matrix power :
 [[ 7 10]
 [15 22]]


## T in ndarray and matrix
• In case of both ndarray and matrix T behaves in the same way

In [68]:
# ** operator in ndarray and matrix
a = np.array([[1,2],[3,4]])
m = np.matrix([[1,2],[3,4]])
ndarray_T = a.T
matrix_T = m.T
print(f'ndarray transpose :\n {ndarray_T}')
print(f'matrix transpose :\n {matrix_T}')

ndarray transpose :
 [[1 3]
 [2 4]]
matrix transpose :
 [[1 3]
 [2 4]]


## Conclusions
• matrix class is the child class of ndarray class. Hence all methods and properties of ndarray class are bydefault available to the matrix class.<br>
• We can use +, *, T, ** for matrix objects also.<br>
• In the case of ndarray, operator performs element level multiplication. But in case of matrix, operator preforms matrix multiplication.<br>
• In the case of ndarray, operator performs power operation at element level. But in the case of matrix, operator performs 'matrix' power.<br>
• matrix class always meant for 2-D array only.<br>
• It is no longer recommended to use.<br>

## Differences between ndarray and matrix

**ndarray**<br>
• It can represent any n-dimension array.<br>
• We can create from any array_like object but not from string.<br>
• * operator meant for element mulitplication but not for dot product.<br>
• ** operator meant for element level power operation<br>
• It is the parent class<br>
• It is the recommended to use<br>

**matrix**
• It can represent only 2-dimension array.<br>
• We can create from either array_like object or from string<br>
• * operator meant for for dot product but not for element mulitplication.<br>
• ** operator meant for for matrix power operation<br>
• It is the child class<br>
• It is not recommended to use and it is deprecated.<br>

# Chapter-18 - Linear Algebra function from linalg module

## Linear Algebra function from linalg module

**numpy.linalg** ==> contains functions to perform linear algebra operations<br>

• inv() ==> to find inverse of a matrix<br>
• matrix_power() ==> to find power of a matrix like A^n<br>
• det ==> to find the determinant of a matrix<br>
• solve() ==> to solve linear algebra equations<br>

## inv() --> to find inverse of a matrix

In [ ]:
import numpy as np
help(np.linalg.inv)

### inverse of 2-D array(matrix)

<img src="images\inv.JPG" alt="inv" width="700" height="600">

In [69]:
# To Find inverse of a matrix
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
print(f"Original Matrix :: \n {a}")
print(f"Inverse of the Matrix :: \n {ainv}")

Original Matrix :: 
 [[1 2]
 [3 4]]
Inverse of the Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]


### How to check the inverse of the matrix is correct or not

• dot(a,ainv) = dot(ainv,a) = eye(a,shape[0])<br>

<img src="images\inv_check.JPG" alt="inv" width="700" height="600">

In [70]:
# To check the inverse of the matrix correct or not
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
dot_produt = np.dot(a,ainv)
i = np.eye(2) # Identity matrix for the shape 2 ==> 2-D Arrray
print(f"Original Matrix :: \n {a}")
print(f"Inverse of the Matrix :: \n {ainv}")
print(f"Dot product of Matrix and Inverse of Matrix :: \n {dot_produt}")
print(f"Identity Matrix(2-D array using eye() function):: \n {i}")

Original Matrix :: 
 [[1 2]
 [3 4]]
Inverse of the Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Dot product of Matrix and Inverse of Matrix :: 
 [[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]
Identity Matrix(2-D array using eye() function):: 
 [[1. 0.]
 [0. 1.]]


### np.allclose()

• np.allclose() ==> method is used to check the matrices are equal at element level Note<br>
• The results of floating point arithmetic varies from platform to platform

In [71]:
# help allclose() function
help(np.allclose)

Help on function allclose in module numpy:

allclose(a, b, rtol=1e-05, atol=1e-08, equal_nan=False)
    Returns True if two arrays are element-wise equal within a tolerance.
    
    The tolerance values are positive, typically very small numbers.  The
    relative difference (`rtol` * abs(`b`)) and the absolute difference
    `atol` are added together to compare against the absolute difference
    between `a` and `b`.
    
    NaNs are treated as equal if they are in the same place and if
    ``equal_nan=True``.  Infs are treated as equal if they are in the same
    place and of the same sign in both arrays.
    
    Parameters
    ----------
    a, b : array_like
        Input arrays to compare.
    rtol : float
        The relative tolerance parameter (see Notes).
    atol : float
        The absolute tolerance parameter (see Notes).
    equal_nan : bool
        Whether to compare NaN's as equal.  If True, NaN's in `a` will be
        considered equal to NaN's in `b` in the output a

In [72]:
# demo for allclose() function
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
dot_produt = np.dot(a,ainv)
np.allclose(dot_produt,i)

True

**Note:** We can find inverse only for square matrices, otherwise we will get error(LinAlgError)

In [73]:
a = np.arange(10).reshape(5,2)
np.linalg.inv(a)

LinAlgError: Last 2 dimensions of the array must be square

### inverse of 3-D array
• 3-D array is the collection of 2-D arrays<br>
• Finding inverse of 3-D array means finding the inverse of every 2-D array

In [74]:
a = np.arange(8).reshape(2,2,2)
ainv = np.linalg.inv(a)
print(f"Original 3-D array :: \n {a}")
print(f"Inverse of 3-D array :: \n {ainv}")

Original 3-D array :: 
 [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
Inverse of 3-D array :: 
 [[[-1.5  0.5]
  [ 1.   0. ]]

 [[-3.5  2.5]
  [ 3.  -2. ]]]


## matrix_power()

**to find power of a matrix like A^n<br>
matrix_power(a, n) ==>** Raise a square matrix to the (integer) power n.<br>

• if n == 0 ==> Identity Matrix<br>
• if n > 0 ==> Normal Power operation<br>
• if n < 0 ==> First inverse and then power operation for absolute value of n abs(n)

In [ ]:
import numpy as np
help(np.linalg.matrix_power)

In [75]:
# if n=0 ==> Identity Matrix
a = np.array([[1,2],[3,4]])
matrix_power = np.linalg.matrix_power(a,0)
print(f"Original 2-D array(Matrix) :: \n {a}")
print(f"Matrix Power of 2-D array :: \n {matrix_power}")

Original 2-D array(Matrix) :: 
 [[1 2]
 [3 4]]
Matrix Power of 2-D array :: 
 [[1 0]
 [0 1]]


In [77]:
# if n > 0 ==> Normal power operation
a = np.array([[1,2],[3,4]])
matrix_power = np.linalg.matrix_power(a,2)
print(f"Original 2-D array(Matrix) :: \n {a}")
print(f"Matrix Power of 2-D array :: \n {matrix_power}")

Original 2-D array(Matrix) :: 
 [[1 2]
 [3 4]]
Matrix Power of 2-D array :: 
 [[ 7 10]
 [15 22]]


In [78]:
# if n < 0 ==> First inverse opeartion and then power operation
a = np.array([[1,2],[3,4]])
matrix_power = np.linalg.matrix_power(a,-2)
print(f"Original 2-D array(Matrix) :: \n {a}")
print(f"Matrix Power of 2-D array :: \n {matrix_power}")

Original 2-D array(Matrix) :: 
 [[1 2]
 [3 4]]
Matrix Power of 2-D array :: 
 [[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [79]:
# dot product of inverse matrix => dot(ainv) * dot(ainv) = result of n < 0 case
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
dot_product = np.dot(ainv,ainv)
print(f"Original 2-D array(Matrix) :: \n {a}")
print(f"Inverse of Matrix :: \n {ainv}")
print(f"Dot product of Inverse of Matrix :: \n {dot_product}")

Original 2-D array(Matrix) :: 
 [[1 2]
 [3 4]]
Inverse of Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Dot product of Inverse of Matrix :: 
 [[ 5.5  -2.5 ]
 [-3.75  1.75]]


In [80]:
# matrix power of inverse matrix and abs(n)
a = np.array([[1,2],[3,4]])
ainv = np.linalg.inv(a)
matrix_power = np.linalg.matrix_power(ainv,2)
print(f"Original 2-D array(Matrix) :: \n {a}")
print(f"Inverse of Matrix :: \n {ainv}")
print(f"Matrix power of Inverse of Matrix and abs(n) :: \n {matrix_power}")

Original 2-D array(Matrix) :: 
 [[1 2]
 [3 4]]
Inverse of Matrix :: 
 [[-2.   1. ]
 [ 1.5 -0.5]]
Matrix power of Inverse of Matrix and abs(n) :: 
 [[ 5.5  -2.5 ]
 [-3.75  1.75]]


<img src="images\matrix_power.JPG" alt="matrix_power" width="700" height="600">

In [81]:
a = np.arange(10).reshape(5,2)
np.linalg.matrix_power(a,2)

LinAlgError: Last 2 dimensions of the array must be square

## det()

**to find the determinant of a matrix**<br>
• determinant of the matrix = ad-bc

<img src="images\det.JPG" alt="det" width="700" height="600">

In [ ]:
import numpy as np
help(np.linalg.det)

### determinant of 2-D arrays

In [82]:
a = np.array([[1,2],[3,4]])
adet = np.linalg.det(a)
print(f"Original Matrix : \n {a}")
print(f"Determinant of Matrix : \n {adet}")

Original Matrix : 
 [[1 2]
 [3 4]]
Determinant of Matrix : 
 -2.0000000000000004


### determinant of 3-D arrays

In [83]:
a = np.arange(9).reshape(3,3)
adet = np.linalg.det(a)
print(f"Original Matrix : \n {a}")
print(f"Determinant of Matrix : \n {adet}")

Original Matrix : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Determinant of Matrix : 
 0.0


**Note:** We can find determinant only for square matrices, otherwise we will get error(LinAlgError)

In [84]:
a = np.arange(10).reshape(5,2)
np.linalg.det(a)

LinAlgError: Last 2 dimensions of the array must be square

## solve()

**to solve linear algebra equations<br>
solve(a, b)** ==> Solve a linear matrix equation, or system of linear scalar equations.<br>

• a : (..., M, M) array_like ==> Coefficient matrix.<br>
• b : {(..., M,), (..., M, K)}, array_like ==> Ordinate or "dependent variable" values.<br>

## 2 variables

### case study:

**Problem:**<br>
• Boys and Girls are attending Durga sir's datascience class.<br>
• For boys fee is $3 and for girls fee is $8.<br>
• For a certain batch 2200 people attented and $10100 fee collected.<br>
• How many boys and girls attended for that batch?<br>

<img src="images\problem.JPG" alt="det" width="700" height="600">

In [85]:
# solution
# x+y = 2200
# 3x+8y=10100
coef = np.array([[1,1],[3,8]])
dep = np.array([2200,10100])
result = np.linalg.solve(coef,dep)
print(f"Coefficient Matrix : \n {coef}")
print(f"Dependent Matrix : \n {dep}")
print(f"Solution array : {result}")
print(f"Type of result : {type(result)}")

Coefficient Matrix : 
 [[1 1]
 [3 8]]
Dependent Matrix : 
 [ 2200 10100]
Solution array : [1500.  700.]
Type of result : <class 'numpy.ndarray'>


3 variables

<img src="images\problem_3.JPG" alt="problem_3" width="700" height="600">

In [86]:
# Finding the values of the 3 variables
# -4x+7y-2z = 2
# x-2y+z = 3
# 2x-3y+z = -4
coef = np.array([[-4,7,-2],[1,-2,1],[2,-3,1]])
dep = np.array([2,3,-4])
result = np.linalg.solve(coef,dep)
print(f"Coefficient Matrix : \n {coef}")
print(f"Dependent Matrix : \n {dep}")
print(f"Solution array : {result}")

Coefficient Matrix : 
 [[-4  7 -2]
 [ 1 -2  1]
 [ 2 -3  1]]
Dependent Matrix : 
 [ 2  3 -4]
Solution array : [-13.  -6.   4.]
