# Chapter-19 - IO operations with Numpy

## I/O operations with Numpy

• We can save/write ndarray objects to a binary file for future purpose.<br>
• Later point of time, when ever these objects are required, we can read from that binary file.<br>
• save() ==> to save/write ndarry object to a file<br>
• load() ==>to read ndarray object from a file<br>

### Syntax
• ***save(file, arr, allow_pickle=True, fix_imports=True)*** ==> Save an array to a binary file in NumPy .npy format.<br>
• ***load(file, mmap_mode=None, allow_pickle=False, fix_imports=True, encoding='ASCII')*** ==> Load arrays or pickled objects from .npy, .npz or pickled
files.

In [ ]:
import numpy as np
help(np.save)

In [ ]:
import numpy as np
help(np.load)

## save() and load() => single ndarray

In [1]:
# Saving ndarray object to a file and read back:(save_read_obj.py)
import numpy as np
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)

#save/serialize ndarray object to a file
np.save('out.npy',a)

#load/deserialize ndarray object from a file
out_array = np.load('out.npy')
print(out_array)

[[10 20 30]
 [40 50 60]]


**Note:**<br>
• The data will be stored in binary form<br>
• File extension should be .npy, otherwise save() function itself will add that extension.<br>
• By using **save()** function we can write only one obejct to the file. If we want to write multiple objects to a file then we should go for **savez()** function.

## savez() and load() => multiple ndarrays

In [ ]:
import numpy as np
help(np.savez)

In [2]:
# Saving mulitple ndarray objects to the binary file:
import numpy as np
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)
b = np.array([[70,80],[90,100]]) #2-D array with shape:(2,2)

#save/serialize ndarrays object to a file
np.savez('out.npz',a,b)

#reading ndarray objects from a file
npzfileobj = np.load('out.npz') #returns NpzFile object
print(f"Type of the npzfileobj : {type(npzfileobj)}")
print(npzfileobj.files)
print(npzfileobj['arr_0'])
print(npzfileobj['arr_1'])

Type of the npzfileobj : <class 'numpy.lib.npyio.NpzFile'>
['arr_0', 'arr_1']
[[10 20 30]
 [40 50 60]]
[[ 70  80]
 [ 90 100]]


In [3]:
# reading the file objets using for loop
import numpy as np
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)
b = np.array([[70,80],[90,100]]) #2-D array with shape:(2,2)

#save/serialize ndarrays object to a file
np.savez('out.npz',a,b)

#reading ndarray objects from a file
npzfileobj = np.load('out.npz') #returns NpzFile object ==> <class 'numpy.lib.npyio.NpzFile'>
print(type(npzfileobj))
print(npzfileobj.files)

for i in npzfileobj:
    print(f"Name of the file : {i}")
    print("Contents in the file :")
    print(npzfileobj[i])
    print("*"*80)

<class 'numpy.lib.npyio.NpzFile'>
['arr_0', 'arr_1']
Name of the file : arr_0
Contents in the file :
[[10 20 30]
 [40 50 60]]
********************************************************************************
Name of the file : arr_1
Contents in the file :
[[ 70  80]
 [ 90 100]]
********************************************************************************


## Note

• **np.save()** ==>Save an array to a binary file in .npy format<br>
• **np.savez()** ==> Save several arrays into a single file in .npz format but in uncompressed form.<br>
• **np.savez_compressed()** ==>Save several arrays into a single file in .npz format but in compressed form.<br>
• **np.load()** ==>To load/read arrays from .npy or .npz files.

## savez_compressed() and load() => ndarray compressed form

In [ ]:
import numpy as np
help(np.savez_compressed)

In [4]:
# compressed form
import numpy as np
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)
b = np.array([[70,80],[90,100]]) #2-D array with shape:(2,2)

#save/serialize ndarrays object to a file
np.savez_compressed('out_compressed.npz',a,b)

#reading ndarray objects from a file
npzfileobj = np.load('out_compressed.npz') #returns NpzFile object
#print(type(npzfileobj))
print(npzfileobj.files)
print(npzfileobj['arr_0'])
print(npzfileobj['arr_1'])

['arr_0', 'arr_1']
[[10 20 30]
 [40 50 60]]
[[ 70  80]
 [ 90 100]]


In [5]:
# Analysys
%ls out.npz out_compressed.npz

 Volume in drive C is OSDisk
 Volume Serial Number is 96FE-AEC2

 Directory of C:\Users\saurabhkumar9\numpy_image


 Directory of C:\Users\saurabhkumar9\numpy_image

07/03/2024  04:58 PM               546 out.npz
07/03/2024  04:58 PM               419 out_compressed.npz
               2 File(s)            965 bytes
               0 Dir(s)  201,076,817,920 bytes free


**We can save object in compressed form, then what is the need of uncompressed form?**<br>

• **compressed form** ==>memory will be saved, but performance down.<br>
• **uncompressed form** ==>memory won't be saved, but performance wise good.<br>

**Note:**<br>
• if we are using **save()** function the file extension: **npy**<br>
• if we are using **savez() or savez_compressed()** functions the file extension: **npz**

## savetxt() and loadtxt() => ndarray object to text file

• To save ndarray object to a text file we will use **savetxt()** function<br>
• To read ndarray object from a text file we will use **loadtxt()** function

In [ ]:
import numpy as np
help(np.savetxt)

In [ ]:
import numpy as np
help(np.loadtxt)

In [6]:
import numpy as np
a = np.array([[10,20,30],[40,50,60]]) #2-D array with shape:(2,3)

#save/serialize ndarrays object to a file
np.savetxt('out.txt',a,fmt='%.1f')

#reading ndarray objects from a file and default dtype is float
out_array1 = np.loadtxt('out.txt')
print("Output array in default format : float")
print(out_array1)

#reading ndarray objects from a file and default dtype is int
print("Output array in int format")
out_array2 = np.loadtxt('out.txt',dtype=int)
print(out_array2)

Output array in default format : float
[[10. 20. 30.]
 [40. 50. 60.]]
Output array in int format
[[10 20 30]
 [40 50 60]]


C:\Users\saurabhkumar9\AppData\Local\Temp\ipykernel_1380\2356838790.py:14: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  out_array2 = np.loadtxt('out.txt',dtype=int)


In [7]:
## save ndarray object(str) into a text file
import numpy as np
a1 = np.array([['Sunny',1000],['Bunny',2000],['Chinny',3000],['Pinny',4000]])

#save this ndarray to a text file
np.savetxt('out.txt',a1) # by default fmt='%.18e'. It will leads to error

TypeError: Mismatch between array dtype ('<U11') and format specifier ('%.18e %.18e')

## savetxt() conclusions

• By using savetxt() we can store ndarray of type 1-D and 2-D only<br>
• If we use 3-D array to store into a file then it will give error

In [8]:
import numpy as np
a = np.arange(24).reshape(2,3,4)
np.savetxt('output.txt',a)

ValueError: Expected 1D or 2D array, got 3D array instead

In [9]:
# to store str ndarray into a file we must specify the fmt parameter as str
import numpy as np
a1 = np.array([['Sunny',1000],['Bunny',2000],['Chinny',3000],['Pinny',4000]])

#save this ndarray to a text file
np.savetxt('out.txt',a1,fmt='%s %s')

#reading ndarray from the text file
a2 = np.loadtxt('out.txt',dtype='str')
print(f"Type of a2(fetching the data from text file) : {type(a2)}")
print(f"The a2 value after fetching the data from text file : \n {a2}")

Type of a2(fetching the data from text file) : <class 'numpy.ndarray'>
The a2 value after fetching the data from text file : 
 [['Sunny' '1000']
 ['Bunny' '2000']
 ['Chinny' '3000']
 ['Pinny' '4000']]


## Creating ndarray object by reading a file

In [10]:
# out.txt:
# -------
# Sunny 1000
# Bunny 2000
# Chinny 3000
# Pinny 4000
# Zinny 5000
# Vinny 6000
# Minny 7000
# Tinny 8000
# creating ndarray from text file data:
import numpy as np
#reading ndarray from the text file
a2 = np.loadtxt('out.txt',dtype='str')
print(f"Type of a2 : {type(a2)}")
print(a2)

Type of a2 : <class 'numpy.ndarray'>
[['Sunny' '1000']
 ['Bunny' '2000']
 ['Chinny' '3000']
 ['Pinny' '4000']]


## Writing ndarray objects to the csv file

• csv - Comma separated Values

In [12]:
import numpy as np
a1 = np.array([[10, 20, 30], [40, 50, 60]])
                           
#save/serialize to a csv file
np.savetxt('out.csv',a1,delimiter=',')

#reading ndarray object from a csv file
a2 = np.loadtxt('out.csv',delimiter=',')
print(a2)

[[10. 20. 30.]
 [40. 50. 60.]]


## Summary:

| Functionality                           | Description                                    | Functions Used                |
|-----------------------------------------|------------------------------------------------|-------------------------------|
| Save one ndarray object                 | to the binary file                             | `save()` and `load()`         |
| Save multiple ndarray objects           | to the binary file in uncompressed form        | `savez()` and `load()`        |
| Save multiple ndarray objects           | to the binary file in compressed form          | `savez_compressed()` and `load()` |
| Save ndarray object                     | to the text file                               | `savetxt()` and `loadtxt()`   |
| Save ndarray object                     | to the csv file                                | `savetxt()` and `loadtxt()` with `delimiter=','` |

# Chapter-20 - Basic Statistics with Numpy

**In Datascience domain, we required to collect,store and analyze huge amount of data. From this data we may required to find some basic statistics like**<br>

• Minimum value<br>
• Maximum value<br>
• Average Value<br>
• Sum of all values<br>
• Mean value<br>
• Median value<br>
• Variance<br>
• Standard deviation etc<br>

## Minimum value

• np.min(a)<br>
• np.amin(a)<br>
• a.min()

In [ ]:
import numpy as np
help(np.min)

### 1-D array

In [13]:
a = np.array([10,5,20,3,25])
print(f"1-D array : {a}")
print(f"np.min(a) value : {np.min(a)}")
print(f"np.amin(a) value : {np.amin(a)}")
print(f"a.min() value : {a.min()}")

1-D array : [10  5 20  3 25]
np.min(a) value : 3
np.amin(a) value : 3
a.min() value : 3


### 2-D array

• axis=None(default) - The array is flattened to 1-D array and find the the min value<br>
• axis=0 - minimum row and that row contains 3 element<br>
• axis=1 - minimum column and that column contains 4 elements<br>
• axis=0 - minimum row and that is by considering all the columns, in that min row value<br>
• axis=1 - minimum column and that is by considering all rows, in that min column value

<img src="images\stats_1.JPG" alt="insert2d" width="600" height="600">

In [14]:
import numpy as np
a = np.array([[100,20,30],[10,50,60],[25,15,18],[4,5,19]])
print(f"array a : \n {a}")
print(f"Minimum value along axis=None : {np.min(a)}")
print(f"Minimum value along axis-0 : {np.min(a,axis=0)}")
print(f"Minimum value along axis-1 : {np.min(a,axis=1)}")

array a : 
 [[100  20  30]
 [ 10  50  60]
 [ 25  15  18]
 [  4   5  19]]
Minimum value along axis=None : 4
Minimum value along axis-0 : [ 4  5 18]
Minimum value along axis-1 : [20 10 15  4]


In [15]:
import numpy as np
a = np.arange(24).reshape(6,4)
print(f"array a : \n {a}")
print(f"Minimum value along axis=None : {np.min(a)}")
print(f"Minimum value along axis-0 : {np.min(a,axis=0)}")
print(f"Minimum value along axis-1 : {np.min(a,axis=1)}")

array a : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
Minimum value along axis=None : 0
Minimum value along axis-0 : [0 1 2 3]
Minimum value along axis-1 : [ 0  4  8 12 16 20]


In [16]:
import numpy as np
a = np.arange(24)
np.random.shuffle(a)
a = a.reshape(6,4)
print(f"array a : \n {a}")
print(f"Minimum value along axis=None : {np.min(a)}")
print(f"Minimum value along axis-0 : {np.min(a,axis=0)}")
print(f"Minimum value along axis-1 : {np.min(a,axis=1)}")

array a : 
 [[19 18 17  5]
 [20 12  2  9]
 [11 14 23  6]
 [21  3  1 22]
 [15  8 13  4]
 [10  0  7 16]]
Minimum value along axis=None : 0
Minimum value along axis-0 : [10  0  1  4]
Minimum value along axis-1 : [5 2 6 1 4 0]


## Maximum value

• np.max(a)<br>
• np.amax(a)<br>
• a.max()

In [ ]:
import numpy as np
help(np.max)

### 1-D array

In [17]:
a = np.array([10,5,20,3,25])
print(f"1-D array : {a}")
print(f"np.max(a) value : {np.max(a)}")
print(f"np.amax(a) value : {np.amax(a)}")
print(f"a.max() value : {a.max()}")

1-D array : [10  5 20  3 25]
np.max(a) value : 25
np.amax(a) value : 25
a.max() value : 25


### 2-D array
• axis=None(default) - The array is flattened to 1-D array and find the the max value<br>
• axis=0 - maximum row and that row contains 3 element<br>
• axis=1 - maximum column and that column contains 4 elements<br>
• axis=0 - maximum row and that is by considering all the columns, in that max row value<br>
• axis=1 - maximum column and that is by considering all rows, in that max column value<br>

<img src="images\stats_2.JPG" alt="insert2d" width="600" height="600">

In [18]:
import numpy as np
a = np.array([[100,20,30],[10,50,60],[25,15,18],[4,5,19]])
print(f"array a : \n {a}")
print(f"Maximum value along axis=None : {np.max(a)}")
print(f"Maximum value along axis-0 : {np.max(a,axis=0)}")
print(f"Maximum value along axis-1 : {np.max(a,axis=1)}")

array a : 
 [[100  20  30]
 [ 10  50  60]
 [ 25  15  18]
 [  4   5  19]]
Maximum value along axis=None : 100
Maximum value along axis-0 : [100  50  60]
Maximum value along axis-1 : [100  60  25  19]


## sum of the elements

• np.sum()<br>
• a.sum()

In [ ]:
import numpy as np
help(np.sum)

### 1-D array

In [19]:
# sum of elements of 1-D array
a = np.arange(4)
print(f"The array a : {a}")
print(f"sum of elements using np.sum(a) :: {np.sum(a)}")
print(f"sum of elements using a.sum() :: {a.sum()}")

The array a : [0 1 2 3]
sum of elements using np.sum(a) :: 6
sum of elements using a.sum() :: 6


### 2-D array
• axis=None(default) - The array is flattened to 1-D array and sum is calculated<br>
• axis=0 - all rows and sum of each column<br>
• axis=1 - all columns and sum of each row<br>

<img src="images\stats_3.JPG" alt="insert2d" width="600" height="600">

In [20]:
a = np.arange(9).reshape(3,3)
print(f"array a : \n {a}")
print(f"Sum along axis=None : {np.sum(a)}")
print(f"Sum along axis-0 : {np.sum(a,axis=0)}")
print(f"Sum along axis-1 : {np.sum(a,axis=1)}")

array a : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Sum along axis=None : 36
Sum along axis-0 : [ 9 12 15]
Sum along axis-1 : [ 3 12 21]


## Mean value

• np.mean(a)<br>
• a.mean()<br>
• Mean is the sum of elements along the specified axis divided by number of elements.

In [ ]:
import numpy as np
help(np.mean)

### 1-D array

In [21]:
a = np.arange(5)
print(f"1-D array : {a}")
print(f"np.mean(a) value : {np.mean(a)}")
print(f"a.mean() value : {a.mean()}")

1-D array : [0 1 2 3 4]
np.mean(a) value : 2.0
a.mean() value : 2.0


### 2-D array

• axis=None(default) - The array is flattened to 1-D array and find the mean(average) value<br>
• axis=0 - rows. Consider columns with all rows and find the average<br>
• axis=1 - columns. Consider rows with all columns and find the average<br>

<img src="images\stats_4.JPG" alt="insert2d" width="600" height="600">

In [22]:
# 2-D array mean
a = np.arange(9).reshape(3,3)
print(f"The original 2-D array : \n {a}")
print(f"Mean of the 2-D array along axis=None : {np.mean(a)}")
print(f"Mean of the 2-D array along axis=0 : {np.mean(a,axis=0)}")
print(f"Mean of the 2-D array along axis=1 : {np.mean(a,axis=1)}")

The original 2-D array : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean of the 2-D array along axis=None : 4.0
Mean of the 2-D array along axis=0 : [3. 4. 5.]
Mean of the 2-D array along axis=1 : [1. 4. 7.]


## Median value

**np.median(a)**<br>
• Median means middle element of the array (sorted form)<br>
• If the array contains even number of elements, then the median is the middle element value<br>
• If the array contains odd number of elements, then the median is the average of 2 middle element values<br>

In [ ]:
import numpy as np
help(np.median)

### 1-D array

In [23]:
a = np.array([10,20,30,40])
b = np.array([10,20,30,40,50])
print(f"The array with even number of elements : {a}")
print(f"Median of the array with even number of elements : {np.median(a)}")
print()
print(f"The array with odd number of elements : {b}")
print(f"Median of the array with odd number of elements : {np.median(b)}")

The array with even number of elements : [10 20 30 40]
Median of the array with even number of elements : 25.0

The array with odd number of elements : [10 20 30 40 50]
Median of the array with odd number of elements : 30.0


In [24]:
# unsorted array(even no of elements) will be converted to sorted array and then
#median is calculated
a = np.array([80,20,60,40])
print(f"The array with even number of elements(unsorted) : {a}")
print("*"*100)
print("This step is calculated internally ")
print(f"sorted form of given array : {np.sort(a)}")
print("*"*100)
print(f"Median of the array with even number of elements : {np.median(a)}")

The array with even number of elements(unsorted) : [80 20 60 40]
****************************************************************************************************
This step is calculated internally 
sorted form of given array : [20 40 60 80]
****************************************************************************************************
Median of the array with even number of elements : 50.0


In [25]:
# unsorted array(odd no of elements) will be converted to sorted array and then
#median is calculated
a = np.array([80,20,60,40,100,140,120])
print(f"The array with even number of elements(unsorted) : {a}")
print("*"*100)
print("This step is calculated internally ")
print(f"sorted form of given array : {np.sort(a)}")
print("*"*100)
print(f"Median of the array with even number of elements : {np.median(a)}")

The array with even number of elements(unsorted) : [ 80  20  60  40 100 140 120]
****************************************************************************************************
This step is calculated internally 
sorted form of given array : [ 20  40  60  80 100 120 140]
****************************************************************************************************
Median of the array with even number of elements : 80.0


### 2-D array
• axis=None(default) - The array is flattened to 1-D array(sorted) and find the median value<br>
• axis=0 - rows. Consider columns with all rows and find the median<br>
• axis=1 - columns. Consider rows with all columns and find the median<br>

<img src="images\stats_5.JPG" alt="insert2d" width="600" height="600">

In [26]:
# 2-D array median
a = np.arange(9).reshape(3,3)
print(f"The original 2-D array(already sorted) : \n {a}")
print(f"Mean of the 2-D array along axis=None : {np.median(a)}")
print(f"Mean of the 2-D array along axis=0 : {np.median(a,axis=0)}")
print(f"Mean of the 2-D array along axis=1 : {np.median(a,axis=1)}")

The original 2-D array(already sorted) : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Mean of the 2-D array along axis=None : 4.0
Mean of the 2-D array along axis=0 : [3. 4. 5.]
Mean of the 2-D array along axis=1 : [1. 4. 7.]


<img src="images\stats_6.JPG" alt="insert2d" width="600" height="600">

In [27]:
# 2-D array median ==> unsorted elements
a = np.array([[22,55,88],[11,44,55],[33,66,99]])
print(f"The original 2-D array(unsorted) : \n {a}")
print(f"Mean of the 2-D array along axis=None : {np.median(a)}")
print(f"Mean of the 2-D array along axis=0 : {np.median(a,axis=0)}")
print(f"Mean of the 2-D array along axis=1 : {np.median(a,axis=1)}")

The original 2-D array(unsorted) : 
 [[22 55 88]
 [11 44 55]
 [33 66 99]]
Mean of the 2-D array along axis=None : 55.0
Mean of the 2-D array along axis=0 : [22. 55. 88.]
Mean of the 2-D array along axis=1 : [55. 44. 66.]


<img src="images\stats_7.JPG" alt="insert2d" width="600" height="600">

In [28]:
# 2-D array median ==> unsorted elements using shuffle
a = np.arange(9)
np.random.shuffle(a)
a = a.reshape(3,3)
print(f"The original 2-D array(unsorted) : \n {a}")
print(f"Mean of the 2-D array along axis=None : {np.median(a)}")
print(f"Mean of the 2-D array along axis=0 : {np.median(a,axis=0)}")
print(f"Mean of the 2-D array along axis=1 : {np.median(a,axis=1)}")

The original 2-D array(unsorted) : 
 [[8 1 4]
 [3 5 2]
 [0 7 6]]
Mean of the 2-D array along axis=None : 4.0
Mean of the 2-D array along axis=0 : [3. 5. 4.]
Mean of the 2-D array along axis=1 : [4. 3. 6.]


## Variance value

**np.var(a)<br>
a.var()**<br>

The variance is a measure of variability. It is calculated by taking the average of squared deviations from the mean.<br>

**• average of<br>
• squared<br>
• deviations from the mean.**<br>

<img src="images\stats_8.JPG" alt="insert2d" width="600" height="600">

In [ ]:
import numpy as np
help(np.var)

### 1-D array

In [29]:
a = np.array([1,2,3,4,5])
print(f"Original 1-D array : {a}")
print(f"Variance of 1-D array unsing np.var(a): {np.var(a)}")
print(f"Variance of 1-D array unsing a.var(): {a.var()}")

Original 1-D array : [1 2 3 4 5]
Variance of 1-D array unsing np.var(a): 2.0
Variance of 1-D array unsing a.var(): 2.0


### 2-D array

• axis=None(default) - The array is flattened to 1-D array(sorted) and find the variance value<br>
• axis=0 - rows. Consider columns with all rows and find the variance<br>
• axis=1 - columns. Consider rows with all columns and find the variance

In [30]:
a = np.arange(6).reshape(2,3)
print(f"Original 2-D array :\n {a}")
print(f"Variance of 2-D array using np.var(a) along axis=None: {np.var(a)}")
print(f"Variance of 2-D array using np.var(a) along axis=0: {np.var(a,axis=0)}")
print(f"Variance of 2-D array using np.var(a) along axis=1: {np.var(a,axis=1)}")

Original 2-D array :
 [[0 1 2]
 [3 4 5]]
Variance of 2-D array using np.var(a) along axis=None: 2.9166666666666665
Variance of 2-D array using np.var(a) along axis=0: [2.25 2.25 2.25]
Variance of 2-D array using np.var(a) along axis=1: [0.66666667 0.66666667]


## Standard Deviation value

• **np.std(a)<br>
• a.std()**<br>
• Variance means the average of squares of deviations from the mean.<br>
• Standard deviation is the **square root of the variance**.

### 1-D array

In [31]:
import math
a = np.array([1,2,3,4,5])
print(f"Original 1-D array : {a}")
print(f"Variance of 1-D array unsing np.var(a): {np.var(a)}")
print(f"Standard Deviation of 1-D array unsing np.std(a): {np.std(a)}")
print(f"Square root of Variannce : {math.sqrt(np.var(a))}")

Original 1-D array : [1 2 3 4 5]
Variance of 1-D array unsing np.var(a): 2.0
Standard Deviation of 1-D array unsing np.std(a): 1.4142135623730951
Square root of Variannce : 1.4142135623730951


### 2-D array

In [32]:
import math
a = np.arange(6).reshape(2,3)
print(f"Original 2-D array :\n {a}")
print("*"*100)
print(f"Variance of 2-D array using np.var(a) along axis=None: {np.var(a)}")
print(f"Standard Deviation of 2-D array using np.std(a) along axis=None: {np.std(a)}")
print(f"Square root of Variannce : {math.sqrt(np.var(a))}")
print("*"*100)
print(f"Variance of 2-D array using np.var(a) along axis=0: {np.var(a,axis=0)}")
print(f"Standard Deviation of 2-D array using np.std(a) along axis=0:{np.std(a,axis=0)}")
print("*"*100)
print(f"Variance of 2-D array using np.var(a) along axis=1: {np.var(a,axis=1)}")
print(f"Standard Deviation of 2-D array using np.std(a) along axis=1:{np.std(a,axis=1)}")
print("*"*100)

Original 2-D array :
 [[0 1 2]
 [3 4 5]]
****************************************************************************************************
Variance of 2-D array using np.var(a) along axis=None: 2.9166666666666665
Standard Deviation of 2-D array using np.std(a) along axis=None: 1.707825127659933
Square root of Variannce : 1.707825127659933
****************************************************************************************************
Variance of 2-D array using np.var(a) along axis=0: [2.25 2.25 2.25]
Standard Deviation of 2-D array using np.std(a) along axis=0:[1.5 1.5 1.5]
****************************************************************************************************
Variance of 2-D array using np.var(a) along axis=1: [0.66666667 0.66666667]
Standard Deviation of 2-D array using np.std(a) along axis=1:[0.81649658 0.81649658]
****************************************************************************************************


## Summary

| Function                  | Description                                        |
|---------------------------|----------------------------------------------------|
| `np.min(a)/np.amin(a)/a.min()` | Returns the minimum value of the array           |
| `np.max(a)/np.amax(a)/a.max()` | Returns the maximum value of the array           |
| `np.sum(a)/a.sum()`           | Returns the Sum of values of the array            |
| `np.mean(a)/a.mean()`         | Returns the arithmetic mean of the array          |
| `np.median(a)`                | Returns median value of the array                 |
| `np.var(a)/a.var()`           | Returns variance of the values in the array       |
| `np.std(a)/a.std()`           | Returns Standard deviation of the values in the array |

# Chapter-21 - Numpy Mathematical Functions

## Numpy Mathematical Functions

• The functions which operates element by element on whole array, are called **universal functions**.<br>
• To perform mathematical operations numpy library contains several universal functions (ufunc).<br>

| Function      | Description                                   | Example Value              |
|---------------|-----------------------------------------------|----------------------------|
| `np.exp(a)`   | Takes e to the power of each value            | e value: 2.7182            |
| `np.sqrt(a)`  | Returns square root of each value             |                            |
| `np.log(a)`   | Returns logarithm of each value               |                            |
| `np.sin(a)`   | Returns the sine of each value                |                            |
| `np.cos(a)`   | Returns the co-sine of each value             |                            |
| `np.tan(a)`   | Returns the tangent of each value             |                            |

In [33]:
import numpy as np
import math
a = np.array([[1,2],[3,4]])
print(f"np.exp(a) value :\n {np.exp(a)}")
print(f"Value of e power 1 ==> {math.exp(1)} ")
print(f"Value of e power 2 ==> {math.exp(2)} ")
print(f"Value of e power 3 ==> {math.exp(3)} ")
print(f"Value of e power 4 ==> {math.exp(4)} ")

np.exp(a) value :
 [[ 2.71828183  7.3890561 ]
 [20.08553692 54.59815003]]
Value of e power 1 ==> 2.718281828459045 
Value of e power 2 ==> 7.38905609893065 
Value of e power 3 ==> 20.085536923187668 
Value of e power 4 ==> 54.598150033144236 


In [34]:
# Mathematical functions
a = np.arange(5)
print(f"exp() on a ==> {np.exp(a)}")
print(f"sqrt() on a ==> {np.sqrt(a)}")
print(f"sin() on a ==> { np.sin(a)}")
print(f"cos() on a ==> {np.cos(a)}")
print(f"tan() on a ==> {np.tan(a)}")
print(f"log() on a :{np.log(a)}")

exp() on a ==> [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
sqrt() on a ==> [0.         1.         1.41421356 1.73205081 2.        ]
sin() on a ==> [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos() on a ==> [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan() on a ==> [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128]
log() on a :[      -inf 0.         0.69314718 1.09861229 1.38629436]


C:\Users\saurabhkumar9\AppData\Local\Temp\ipykernel_1380\1298094331.py:8: RuntimeWarning: divide by zero encountered in log
  print(f"log() on a :{np.log(a)}")


# Chapter-22 - How to find unique items and count

**How to find unique items and count**<br>

using unique() function we can find the unique items and their count in ndarray
<br>
**unique(ar, return_index=False, return_inverse=False, return_counts=False, axis=None) ==> Find the unique elements of an array.**<br>

**Returns the sorted unique elements of an array.** <br>

**There are three optional outputs in addition to the unique elements:**<br>
• the indices of the input array that give the unique values ==> return_index<br>
• the indices of the unique array that reconstruct the input array<br>
• the number of times each unique value comes up in the input array ==>return_counts<br>

In [ ]:
import numpy as np
help(np.unique)

## Get array with unique elements

In [35]:
a = np.array([1,1,2,3,4,2,3,4,4,1,2,3,4,5,5,6])
print(f"Original array : {a}")
print(f"Unique elements in the array using np.unique(a) : {np.unique(a)}")

Original array : [1 1 2 3 4 2 3 4 4 1 2 3 4 5 5 6]
Unique elements in the array using np.unique(a) : [1 2 3 4 5 6]


## Get indices also

In [36]:
a = np.array([1,1,2,3,4,2,3,4,4,1,2,3,4,5,5,6])
items,indices = np.unique(a,return_index=True)
print(f"Original array : {a}")
print(f"Unique Elements :{items}")
print(f"indices of unique elements: {indices}")

Original array : [1 1 2 3 4 2 3 4 4 1 2 3 4 5 5 6]
Unique Elements :[1 2 3 4 5 6]
indices of unique elements: [ 0  2  3  4 13 15]


## To get count also

In [37]:
a = np.array([1,1,2,3,4,2,3,4,4,1,2,3,4,5,5,6])
items,counts = np.unique(a,return_counts=True)
print(f"Original array : {a}")
print(f"Unique Elements :{items}")
print(f"count of unique elements: {counts}")

Original array : [1 1 2 3 4 2 3 4 4 1 2 3 4 5 5 6]
Unique Elements :[1 2 3 4 5 6]
count of unique elements: [3 3 3 4 2 1]


## To get all

In [38]:
a = np.array([1,1,2,3,4,2,3,4,4,1,2,3,4,5,5,6])
items,indices,counts = np.unique(a,return_index=True,return_counts=True)
print(f"Original array : {a}")
print(f"Unique Elements :{items}")
print(f"indices of unique elements: {indices}")
print(f"count of unique elements: {counts}")

Original array : [1 1 2 3 4 2 3 4 4 1 2 3 4 5 5 6]
Unique Elements :[1 2 3 4 5 6]
indices of unique elements: [ 0  2  3  4 13 15]
count of unique elements: [3 3 3 4 2 1]


In [39]:
# To get all in a program
import numpy as np
a = np.array(['a','a','b','c','a','a','b','c','a','b','d'])
items,indices,counts = np.unique(a,return_index=True,return_counts=True)
for item,index,count in zip(np.nditer(items),np.nditer(indices),np.nditer(counts)):
    print(f"Element '{item}' occurred {count} times and its first occurrence index:{index}")

Element 'a' occurred 5 times and its first occurrence index:0
Element 'b' occurred 3 times and its first occurrence index:2
Element 'c' occurred 2 times and its first occurrence index:3
Element 'd' occurred 1 times and its first occurrence index:10
